# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Cavalli_IC_outlet_TauDEM.py
# Created on: 2026-04-11 12:45:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Cavalli_IC_outlet_TauDEM <Workspace> <Pits_Removed_DTM> <Cell_Size> <Weighting_Factor> <Index_of_Connectivity> 
# Description: 
# Computation of the Index of Connectivity (Cavalli et al., 2013)
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx")

# Script arguments
Workspace = arcpy.GetParameterAsText(0)
if Workspace == '#' or not Workspace:
    Workspace = "C:\\temp\\cavalli" # provide a default value if unspecified

Pits_Removed_DTM = arcpy.GetParameterAsText(1)
if Pits_Removed_DTM == '#' or not Pits_Removed_DTM:
    Pits_Removed_DTM = "%Workspace%\\dtmfillok.tif" # provide a default value if unspecified

Cell_Size = arcpy.GetParameterAsText(2)
if Cell_Size == '#' or not Cell_Size:
    Cell_Size = "2.5" # provide a default value if unspecified

Weighting_Factor = arcpy.GetParameterAsText(3)
if Weighting_Factor == '#' or not Weighting_Factor:
    Weighting_Factor = "%Workspace%\\w.tif" # provide a default value if unspecified

Index_of_Connectivity = arcpy.GetParameterAsText(4)
if Index_of_Connectivity == '#' or not Index_of_Connectivity:
    Index_of_Connectivity = "%Workspace%\\icOutlet.tif" # provide a default value if unspecified

# Local variables:
dtmfillokslp_tif = "%Workspace%\\dtmfillokslp.tif"
dtmfillokp_tif = "%Workspace%\\dtmfillokp.tif"
fillad8_tif = "%Workspace%\\dtmfillokad8.tif"
flowd8_tif = "%scratchWorkspace%\\flowd8.tif"
flowdir_tif = "%Workspace%\\flowdir.tif"
dtmfillokang_tif = "%Workspace%\\dtmfillokang.tif"
accW_tif = "%Workspace%\\accW.tif"
dtmfilloksca2_tif = "%Workspace%\\dtmfilloksca2.tif"
resolution_tif = "%Workspace%\\resolution.tif"
ACCfinal_tif = "%scratchWorkspace%\\ACCfinal.tif"
cmean_tif = "%Workspace%\\cmean.tif"
dtmfilloksd8_tif = "%Workspace%\\dtmfilloksd8.tif"
s_tif = "%Workspace%\\s.tif"
accS_tif = "%Workspace%\\accS.tif"
smean_tif = "%Workspace%\\smean.tif"
Dup_tif = "%Workspace%\\Dup.tif"
invCS_tif = "%Workspace%\\invCS.tif"
X_tif = "%Workspace%\\X.tif"
Ddn_tif = "%Workspace%\\Ddn.tif"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = Workspace
arcpy.env.snapRaster = Pits Removed DTM
arcpy.env.extent = Pits Removed DTM
arcpy.env.cellSize = "MAXOF"
arcpy.env.mask = Pits Removed DTM

# Process: D-Infinity Flow Directions
arcpy.gp.toolbox = "C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx";
# Warning: the toolbox C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.DinfFlowDir(...) with arcpy.DinfFlowDir_ALIAS(...)
arcpy.gp.DinfFlowDir(Pits_Removed_DTM, "8", dtmfillokang_tif, dtmfillokslp_tif)

# Process: D8 Flow Directions
arcpy.gp.toolbox = "C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx";
# Warning: the toolbox C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.D8FlowDir(...) with arcpy.D8FlowDir_ALIAS(...)
arcpy.gp.D8FlowDir(Pits_Removed_DTM, "8", dtmfillokp_tif, dtmfilloksd8_tif)

# Process: D8 Contributing Area
arcpy.gp.toolbox = "C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx";
# Warning: the toolbox C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.D8ContributingArea(...) with arcpy.D8ContributingArea_ALIAS(...)
arcpy.gp.D8ContributingArea(dtmfillokp_tif, "", "", "false", "8", fillad8_tif)

# Process: Reclassify
arcpy.gp.Reclassify_sa(Pits_Removed_DTM, "Value", "1 1;2 128;3 64;4 32;5 16;6 8;7 4;8 2", flowd8_tif, "DATA")

# Process: Integrating Sinks and Targets into D8 Flow directions
arcpy.gp.RasterCalculator_sa("\"%flowd8.tif%\"", flowdir_tif)

# Process: D-Infinity Contributing Area (2)
arcpy.gp.toolbox = "C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx";
# Warning: the toolbox C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.AreaDinf(...) with arcpy.AreaDinf_ALIAS(...)
arcpy.gp.AreaDinf(dtmfillokang_tif, "", Weighting_Factor, "false", "8", accW_tif)

# Process: D-Infinity Contributing Area
arcpy.gp.toolbox = "C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx";
# Warning: the toolbox C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.AreaDinf(...) with arcpy.AreaDinf_ALIAS(...)
arcpy.gp.AreaDinf(dtmfillokang_tif, "", "", "false", "8", dtmfilloksca2_tif)

# Process: Create Constant Raster
arcpy.gp.CreateConstantRaster_sa(resolution_tif, Cell_Size, "FLOAT", Pits_Removed_DTM, Pits_Removed_DTM)

# Process: Divide
arcpy.gp.Divide_sa(dtmfilloksca2_tif, resolution_tif, ACCfinal_tif)

# Process: Computing C mean
arcpy.gp.RasterCalculator_sa("(\"%accW.tif%\" + \"%Weighting Factor%\") / \"%ACCfinal.tif%\"", cmean_tif)

# Process: Imposing upper and lower limits to Slope
arcpy.gp.RasterCalculator_sa("Con(\"%dtmfilloksd8.tif%\"  < 0.005, 0.005, Con(\"%dtmfilloksd8.tif%\"> 1, 1, \"%dtmfilloksd8.tif%\"))", s_tif)

# Process: accumulating S
arcpy.gp.toolbox = "C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx";
# Warning: the toolbox C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.AreaDinf(...) with arcpy.AreaDinf_ALIAS(...)
arcpy.gp.AreaDinf(dtmfillokang_tif, "", s_tif, "false", "8", accS_tif)

# Process: Computing S mean
arcpy.gp.RasterCalculator_sa("(\"%accS.tif%\" + \"%s.tif%\") / \"%ACCfinal.tif%\"", smean_tif)

# Process: Computing Upslope Component
arcpy.gp.RasterCalculator_sa("\"%cmean.tif%\" * \"%smean.tif%\" * SquareRoot(\"%ACCfinal.tif%\" * \"%resolution.tif%\" * \"%resolution.tif%\")", Dup_tif)

# Process: Computing 1/(W*S)
arcpy.gp.RasterCalculator_sa("1 / (\"%Weighting Factor%\"*\"%s.tif%\")", invCS_tif)

# Process: Flow Length
arcpy.gp.FlowLength_sa(flowd8_tif, X_tif, "DOWNSTREAM", invCS_tif)

# Process: Computing Downslope Component
arcpy.gp.RasterCalculator_sa("(\"%X.tif%\" == 0 * \"%invCS.tif%\") + \"%X.tif%\"", Ddn_tif)

# Process: Computing Connectivity Index
arcpy.gp.RasterCalculator_sa("Log10(\"%Dup.tif%\" / \"%Ddn.tif%\")", Index_of_Connectivity)

